type RepositoryBinding={id:string;binding_sha256:string;repository_id:number|string;repository_full_name:string;ref:string};
export type StudioComputeAssertionInput={userId:string;workspaceId:string;projectId:string;role:string;objective:string;binding:RepositoryBinding;runtimeProvider?:StudioRuntimeProvider};
export type StudioRuntimeProvider="container"|"google_cloud_shell"|"cloud_run"|"google_cloud_shell"|"cloud_run";
export type StudioComputeAssertionClaims={v:1;iss:"griot-studio";aud:"griot-connected-compute";sub:string;workspaceId:string;studioProjectId:string;bindingId:string;bindingSha256:string;objectiveSha256:string;scope:"run.start";runtimeProvider:StudioRuntimeProvider;repository:{provider:"github";id:string;fullName:string;ref:string};role:string;jti:string;iat:number;exp:number};
export type StudioComputeAssertion={token:string;jti:string;objectiveSha256:string;bindingSha256:string;expiresAt:string};
export class StudioComputeAssertionIssueError extends Error{};export class StudioComputeAssertionVerifyError extends Error{};

export async function createStudioComputeAssertion(input:StudioComputeAssertionInput):Promise<StudioComputeAssertion>{const objective=input.objective.trim();if(!objective||objective.length>20_000)throw new StudioComputeAssertionIssueError("Compute objective must contain 1-20000 characters");validateBinding(input.binding);const provider=input.runtimeProvider??runtimeProvider(),key=await assertionKey(),now=Math.floor(Date.now()/1000),exp=now+60,objectiveSha256=await sha256(objective),jti=crypto.randomUUID();const header={alg:"HS256",typ:"GRIOT-STUDIO-COMPUTE",v:1} as const;const payload:StudioComputeAssertionClaims={v:1,iss:"griot-studio",aud:"griot-connected-compute",sub:input.userId,workspaceId:input.workspaceId,studioProjectId:input.projectId,bindingId:input.binding.id,bindingSha256:input.binding.binding_sha256.toLowerCase(),objectiveSha256,scope:"run.start",runtimeProvider:provider,repository:{provider:"github",id:String(input.binding.repository_id),fullName:input.binding.repository_full_name,ref:input.binding.ref},role:input.role,jti,iat:now,exp};const encodedHeader=base64url(new TextEncoder().encode(JSON.stringify(header))),encodedPayload=base64url(new TextEncoder().encode(JSON.stringify(payload))),signed=`${encodedHeader}.${encodedPayload}`,signature=new Uint8Array(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(signed)));return{token:`${signed}.${base64url(signature)}`,jti,objectiveSha256,bindingSha256:input.binding.binding_sha256.toLowerCase(),expiresAt:new Date(exp*1000).toISOString()};}

export async function verifyStudioComputeAssertion(token:string):Promise<StudioComputeAssertionClaims>{const parts=token.split(".");if(parts.length!==3||parts.some(part=>!part))throw new StudioComputeAssertionVerifyError("Compute assertion is malformed");const[encodedHeader,encodedPayload,encodedSignature]=parts as[string,string,string];let header:Record<string,unknown>,claims:StudioComputeAssertionClaims;try{header=JSON.parse(new TextDecoder().decode(decodeBase64url(encodedHeader)));claims=JSON.parse(new TextDecoder().decode(decodeBase64url(encodedPayload))) as StudioComputeAssertionClaims;}catch{throw new StudioComputeAssertionVerifyError("Compute assertion payload is malformed");}if(header.alg!=="HS256"||header.typ!=="GRIOT-STUDIO-COMPUTE"||header.v!==1)throw new StudioComputeAssertionVerifyError("Compute assertion header is not accepted");const key=await assertionKey(),verified=await crypto.subtle.verify("HMAC",key,decodeBase64url(encodedSignature),new TextEncoder().encode(`${encodedHeader}.${encodedPayload}`));if(!verified)throw new StudioComputeAssertionVerifyError("Compute assertion signature is invalid");validateClaims(claims);return claims;}

export function runtimeProvider():StudioRuntimeProvider{const value=(Deno.env.get("GRIOT_STUDIO_RUNTIME_PROVIDER")||"container").trim();if(value==="container"||value==="cloud_run"||value==="google_cloud_shell")return value;throw new StudioComputeAssertionIssueError("GRIOT_STUDIO_RUNTIME_PROVIDER must be cloudflare_sandbox, cloud_run or google_cloud_shell");}
function validateBinding(binding:RepositoryBinding){if(!UUID_RE.test(binding.id))throw new StudioComputeAssertionIssueError("Verified repository binding id is invalid");if(!SHA_RE.test(binding.binding_sha256))throw new StudioComputeAssertionIssueError("Verified repository binding hash is invalid");const repositoryId=String(binding.repository_id);if(!/^[1-9][0-9]{0,19}$/.test(repositoryId))throw new StudioComputeAssertionIssueError("Verified repository id is invalid");if(!FULL_NAME_RE.test(binding.repository_full_name))throw new StudioComputeAssertionIssueError("Verified repository full name is invalid");if(!binding.ref||binding.ref.length>240)throw new StudioComputeAssertionIssueError("Verified repository ref is invalid");}
function validateClaims(claims:StudioComputeAssertionClaims){const now=Math.floor(Date.now()/1000);if(!claims||claims.v!==1||claims.iss!=="griot-studio"||claims.aud!=="griot-connected-compute"||claims.scope!=="run.start"||!(["container","cloud_run","google_cloud_shell"] as string[]).includes(claims.runtimeProvider)||!UUID_RE.test(claims.sub)||!UUID_RE.test(claims.workspaceId)||!UUID_RE.test(claims.studioProjectId)||!UUID_RE.test(claims.bindingId)||!UUID_RE.test(claims.jti)||!SHA_RE.test(claims.bindingSha256)||!SHA_RE.test(claims.objectiveSha256)||claims.repository?.provider!=="github"||!/^[1-9][0-9]{0,19}$/.test(claims.repository?.id||"")||!FULL_NAME_RE.test(claims.repository?.fullName||"")||!claims.repository?.ref||claims.repository.ref.length>240||typeof claims.role!=="string"||!claims.role||claims.role.length>80||!Number.isInteger(claims.iat)||!Number.isInteger(claims.exp)||claims.exp<=claims.iat||claims.exp-claims.iat>120)throw new StudioComputeAssertionVerifyError("Compute assertion claims are invalid");if(claims.iat>now+10)throw new StudioComputeAssertionVerifyError("Compute assertion is not valid yet");if(claims.exp<=now-10)throw new StudioComputeAssertionVerifyError("Compute assertion has expired");}
async function assertionKey():Promise<CryptoKey>{const encoded=Deno.env.get("GRIOT_STUDIO_COMPUTE_ASSERTION_KEY")||"";let raw:Uint8Array;try{raw=decodeBase64(encoded);}catch{throw new StudioComputeAssertionIssueError("GRIOT_STUDIO_COMPUTE_ASSERTION_KEY must be Base64");}if(raw.length<32)throw new StudioComputeAssertionIssueError("GRIOT_STUDIO_COMPUTE_ASSERTION_KEY must decode to at least 32 bytes");return crypto.subtle.importKey("raw",raw,{name:"HMAC",hash:"SHA-256"},false,["sign","verify"]);}
async function sha256(value:string){const digest=new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)));return Array.from(digest).map(byte=>byte.toString(16).padStart(2,"0")).join("");}
function decodeBase64(value:string):Uint8Array{const normalized=value.trim();if(!normalized||!/^[A-Za-z0-9+/]+={0,2}$/.test(normalized))throw new Error("invalid base64");const binary=atob(normalized);return Uint8Array.from(binary,char=>char.charCodeAt(0));}
function decodeBase64url(value:string):Uint8Array{if(!/^[A-Za-z0-9_-]+$/.test(value))throw new Error("invalid base64url");const normalized=value.replace(/-/g,"+").replace(/_/g,"/"),padded=normalized+"=".repeat((4-normalized.length%4)%4);return decodeBase64(padded);}
function base64url(bytes:Uint8Array):string{let binary="";for(let offset=0;offset<bytes.length;offset+=0x8000)binary+=String.fromCharCode(...bytes.subarray(offset,offset+0x8000));return btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
const UUID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const SHA_RE=/^[0-9a-f]{64}$/i;
const FULL_NAME_RE=/^[A-Za-z0-9_.-]{1,100}\/[A-Za-z0-9_.-]{1,100}$/;
