import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient, type SupabaseClient, type User } from "npm:@supabase/supabase-js@^2";

type Row = Record<string, any>;
type Ctx = { user: User; workspaceId: string; role: string; db: SupabaseClient; authorization: string };
class ApiError extends Error { constructor(readonly status: number, message: string) { super(message); } }

const ALLOWED = new Set([
  "https://griot.pt", "https://canary.griot.pt", "https://studio-canary.griot.pt",
  "http://localhost:3000", "http://127.0.0.1:3000", "http://localhost:5173", "http://127.0.0.1:5173",
]);
function config() {
  const url=Deno.env.get("SUPABASE_URL")||"",anon=Deno.env.get("SUPABASE_ANON_KEY")||Deno.env.get("SUPABASE_PUBLISHABLE_KEY")||"",service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||Deno.env.get("SUPABASE_SECRET_KEY")||"";
  const gatewayUrl=(Deno.env.get("GRIOT_STUDIO_EXECUTION_GATEWAY_URL")||"").replace(/\/+$/,"");
  const gatewayKey=Deno.env.get("GRIOT_EXECUTION_GATEWAY_INTERNAL_KEY")||"",googleClientId=Deno.env.get("GOOGLE_OAUTH_CLIENT_ID")||"";
  if(!url||!anon||!service) throw new ApiError(503,"Supabase server keys are not configured");
  if(!gatewayUrl||!/^https?:\/\//.test(gatewayUrl)) throw new ApiError(503,"Studio execution gateway URL is not configured");
  if(gatewayKey.length<32) throw new ApiError(503,"Studio execution gateway key is not configured");
  return {url,anon,service,gatewayUrl,gatewayKey,googleClientId};
}
function cors(req:Request){ const origin=req.headers.get("origin")||""; const h=new Headers({"access-control-allow-methods":"GET,POST,PUT,DELETE,OPTIONS","access-control-allow-headers":"authorization,apikey,content-type,x-griot-workspace-id,last-event-id,x-requested-with","access-control-expose-headers":"content-type,cache-control","access-control-max-age":"86400",vary:"Origin"}); if(!origin||ALLOWED.has(origin)) h.set("access-control-allow-origin",origin||"https://griot.pt"); return h; }
function json(req:Request,data:unknown,status=200){ const headers=cors(req); headers.set("content-type","application/json; charset=utf-8"); headers.set("cache-control","no-store"); return new Response(JSON.stringify(data),{status,headers}); }
function pathOf(req:Request){ return new URL(req.url).pathname.replace(/^\/functions\/v1\/griot-studio-compute/,"").replace(/^\/griot-studio-compute/,"")||"/"; }
function userClient(req:Request){ const cfg=config(),authorization=req.headers.get("authorization")||""; return createClient(cfg.url,cfg.anon,{auth:{persistSession:false,autoRefreshToken:false},global:authorization?{headers:{Authorization:authorization}}:undefined}); }
function adminClient(){ const cfg=config(); return createClient(cfg.url,cfg.service,{auth:{persistSession:false,autoRefreshToken:false}}); }
async function auth(req:Request):Promise<Ctx>{ const authorization=req.headers.get("authorization")||""; if(!authorization.toLowerCase().startsWith("bearer ")) throw new ApiError(401,"Authentication required"); const user=await userClient(req).auth.getUser(); if(user.error||!user.data.user) throw new ApiError(401,"Invalid or expired session"); const db=adminClient(),requested=req.headers.get("x-griot-workspace-id")?.trim()||""; let query=db.from("griot_workspace_members").select("workspace_id,role,created_at").eq("user_id",user.data.user.id).order("created_at",{ascending:true}); query=requested?query.eq("workspace_id",requested):query.limit(1); const member=await query.maybeSingle(); if(member.error||!member.data) throw new ApiError(403,"No workspace access"); return {user:user.data.user,workspaceId:member.data.workspace_id,role:member.data.role,db,authorization}; }
async function body(req:Request):Promise<Row>{ try{const value=await req.json(); if(!value||typeof value!=="object"||Array.isArray(value)) throw new Error("invalid"); return value as Row;}catch{throw new ApiError(400,"Invalid JSON body");} }
async function project(c:Ctx,id:string):Promise<Row>{ if(!uuid(id)) throw new ApiError(400,"Project id is invalid"); const result=await c.db.from("griot_studio_projects").select("id,workspace_id,owner_id,name").eq("id",id).eq("workspace_id",c.workspaceId).maybeSingle(); if(result.error) throw new ApiError(500,"Could not load Studio project"); if(!result.data) throw new ApiError(404,"Studio project not found"); return result.data as Row; }
async function runMapping(c:Ctx,runId:string,projectId:string):Promise<Row>{ await project(c,projectId); const mapping=await c.db.from("griot_studio_compute_runs").select("internal_run_id,project_id,user_id,status,runtime_id").eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("internal_run_id",runId).eq("user_id",c.user.id).maybeSingle(); if(mapping.error) throw new ApiError(500,"Could not authorize Connected Compute run"); if(!mapping.data) throw new ApiError(404,"Connected Compute run not found"); return mapping.data as Row; }
async function latestReadyRun(c:Ctx,projectId:string):Promise<Row>{ await project(c,projectId); const result=await c.db.from("griot_studio_compute_runs").select("internal_run_id,runtime_id,connection_id,status,updated_at").eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("user_id",c.user.id).eq("status","ready").not("runtime_id","is",null).order("updated_at",{ascending:false}).limit(1).maybeSingle(); if(result.error) throw new ApiError(500,"Could not resolve the active Connected Compute workspace"); if(!result.data) throw new ApiError(409,"Prepare a Connected Compute runtime for this project before using Code or Preview"); return result.data as Row; }
async function agentFullAccess(c:Ctx,projectId:string):Promise<boolean>{ await project(c,projectId); const result=await c.db.from("griot_studio_agent_permissions").select("full_access").eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("user_id",c.user.id).maybeSingle(); if(result.error) throw new ApiError(500,"Could not load Studio agent permission"); return result.data?.full_access===true; }
async function setAgentFullAccess(c:Ctx,projectId:string,fullAccess:boolean):Promise<void>{ const p=await project(c,projectId); if(p.owner_id!==c.user.id&&!["owner","admin"].includes(c.role)) throw new ApiError(403,"Project agent permission cannot be changed by this user"); const result=await c.db.from("griot_studio_agent_permissions").upsert({workspace_id:c.workspaceId,project_id:projectId,user_id:c.user.id,full_access:fullAccess,updated_at:new Date().toISOString()},{onConflict:"workspace_id,project_id,user_id"}); if(result.error) throw new ApiError(500,"Could not persist Studio agent permission"); }
async function callStudioAssertion(req:Request,c:Ctx,projectId:string,objective:string,connectionId?:string,runtimeProvider?:string){ const cfg=config(); const response=await fetch(`${cfg.url}/functions/v1/griot-studio/projects/${projectId}/compute/assertion`,{method:"POST",headers:{authorization:c.authorization,apikey:cfg.anon,"content-type":"application/json","x-griot-workspace-id":c.workspaceId,"x-griot-execution-gateway-key":cfg.gatewayKey},body:JSON.stringify({objective,...(connectionId?{connectionId}:{}),...(runtimeProvider?{runtimeProvider}:{})}),signal:AbortSignal.timeout(30000)}); return expectJson(response,"Studio compute authority"); }
async function callGateway(path:string,init:RequestInit={}){ const cfg=config(),headers=new Headers(init.headers); headers.set("x-griot-execution-gateway-key",cfg.gatewayKey); if(init.body&&!headers.has("content-type")) headers.set("content-type","application/json"); return fetch(`${cfg.gatewayUrl}${path}`,{...init,headers,signal:init.signal??AbortSignal.timeout(180000)}); }
function gatewayScope(c:Ctx,projectId?:string):HeadersInit{return {"x-griot-external-user-id":c.user.id,"x-griot-external-workspace-id":c.workspaceId,...(projectId?{"x-griot-external-project-id":projectId}:{})};}
async function expectJson(response:Response,label:string):Promise<Row>{ const text=await response.text(); let payload:Row={}; try{payload=text?JSON.parse(text) as Row:{}}catch{throw new ApiError(502,`${label} returned non-JSON data`);} if(!response.ok) throw new ApiError(response.status>=500?502:response.status,String(payload.message||payload.error||`${label} failed`).slice(0,1000)); return payload; }
async function requireAgentBridge(req:Request):Promise<void>{ const expected=config().gatewayKey,actual=req.headers.get("x-griot-execution-gateway-key")||""; if(actual.length<32) throw new ApiError(403,"Studio agent tool bridge is forbidden"); const [left,right]=await Promise.all([crypto.subtle.digest("SHA-256",new TextEncoder().encode(expected)),crypto.subtle.digest("SHA-256",new TextEncoder().encode(actual))]); const a=new Uint8Array(left),b=new Uint8Array(right); let different=a.length^b.length; const length=Math.min(a.length,b.length); for(let i=0;i<length;i+=1) different|=a[i]^b[i]; if(different!==0) throw new ApiError(403,"Studio agent tool bridge is forbidden"); }
async function proxyProjectWorkspace(req:Request,c:Ctx,projectId:string,suffix:string,method:string,actor:"human"|"agent"="human"){ const ready=await latestReadyRun(c,projectId),runId=String(ready.internal_run_id||""); if(!uuid(runId)) throw new ApiError(409,"Connected Compute workspace has no valid run identity"); const headers=new Headers(gatewayScope(c,projectId)); if(actor==="agent") headers.set("x-griot-runtime-actor","agent"); let requestBody:string|undefined; if(method!=="GET") requestBody=JSON.stringify(await body(req)); const response=await callGateway(`/studio-connected-compute/runs/${runId}/workspace/${suffix}`,{method,headers,...(requestBody!==undefined?{body:requestBody}:{})}); return json(req,await expectJson(response,`Connected Compute workspace ${suffix}`),response.status); }
async function executeAgentCommand(req:Request,c:Ctx,projectId:string,toolInput:Row,fullAccess:boolean):Promise<Response>{ const ready=await latestReadyRun(c,projectId),runId=String(ready.internal_run_id||""),program=String(toolInput.program||"").trim(); if(!program||program.length>1000||/[\r\n\0]/.test(program)) throw new ApiError(400,"Agent command program is invalid"); const args=Array.isArray(toolInput.args)?toolInput.args.map(String):[]; if(args.length>500||args.some((arg)=>arg.length>20000||arg.includes("\0"))) throw new ApiError(400,"Agent command arguments are invalid"); const softTimeoutMs=boundedInt(toolInput.softTimeoutMs,120000,1000,24*60*60_000),hardTimeoutMs=boundedInt(toolInput.hardTimeoutMs,180000,softTimeoutMs,24*60*60_000); const response=await callGateway(`/studio-connected-compute/runs/${runId}/execute`,{method:"POST",headers:{...gatewayScope(c,projectId),"x-griot-runtime-actor":"agent","x-griot-agent-full-access":fullAccess?"true":"false"},body:JSON.stringify({...(toolInput.requestId&&uuid(toolInput.requestId)?{requestId:toolInput.requestId}:{}),program,args,softTimeoutMs,hardTimeoutMs}),signal:AbortSignal.timeout(hardTimeoutMs+30000)}); const payload=await expectJson(response,"Connected Compute agent command"),state=String(payload.state||""); if(state==="approval_required") await c.db.from("griot_studio_compute_runs").update({status:"approval_required",updated_at:new Date().toISOString()}).eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("internal_run_id",runId).eq("user_id",c.user.id); else if(state==="completed") await c.db.from("griot_studio_compute_runs").update({status:"ready",updated_at:new Date().toISOString()}).eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("internal_run_id",runId).eq("user_id",c.user.id); return json(req,payload,response.status); }
function boundedInt(value:unknown,fallback:number,min:number,max:number){const n=Number(value);return Number.isSafeInteger(n)?Math.min(max,Math.max(min,n)):fallback;}


async function reconcileSandboxStart(_req:Request,c:Ctx,projectId:string,assertion:string):Promise<Row|null>{let claims:Row={};try{const parts=assertion.split(".");if(parts.length<2)return null;const decoded=JSON.parse(new TextDecoder().decode(base64UrlDecode(parts[1]))) as Row;claims=decoded;}catch{return null;}const jti=String(claims.jti||"").trim();if(!jti||!uuid(jti))return null;const headers=gatewayScope(c,projectId);for(let attempt=0;attempt<12;attempt+=1){const response=await callGateway(`/studio-connected-compute/sandbox/runs/by-assertion/${encodeURIComponent(jti)}`,{method:"GET",headers,signal:AbortSignal.timeout(4000)});if(response.ok){const payload=await expectJson(response,"Connected Compute Sandbox reconciliation"),run=payload.run as Row|undefined;if(run&&String(run.state||"")==="ready"&&uuid(run.id)&&uuid(run.taskId)&&uuid(run.runtimeId)&&uuid(run.connectionId)){return {run:{...run,state:"ready"},events:`/studio-connected-compute/runs/${run.id}/events`};}if(run&&["failed","cancelled"].includes(String(run.state||"")))return null;}if(response.status>=400&&response.status!==404&&response.status<500)return null;await new Promise(resolve=>setTimeout(resolve,2500));}return null;}
function base64UrlDecode(value:string):Uint8Array{const normalized=value.replace(/-/g,"+").replace(/_/g,"/")+"=".repeat((4-value.length%4)%4);const binary=atob(normalized);const out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)out[i]=binary.charCodeAt(i);return out;}
async function dispatch(req:Request):Promise<Response>{
  if(req.method==="OPTIONS") return new Response(null,{status:204,headers:cors(req)});
  const path=pathOf(req); if(req.method==="GET"&&path==="/live") return json(req,{ok:true,service:"griot-studio-compute",runtime:"supabase-edge-functions"});
  const c=await auth(req);
  if(req.method==="GET"&&path==="/google/config"){const cfg=config();return json(req,{enabled:Boolean(cfg.googleClientId),clientId:cfg.googleClientId||null,scope:"https://www.googleapis.com/auth/cloud-platform",uxMode:"popup",redirectOrigin:new URL(req.headers.get("origin")||"https://griot.pt").origin});}
  if(req.method==="POST"&&path==="/google/exchange"){if(req.headers.get("x-requested-with")!=="XmlHttpRequest") throw new ApiError(403,"Google popup authorization hand-off is invalid");const input=await body(req),code=String(input.code||""),label=String(input.label||"Google Cloud Shell").trim().slice(0,200);if(code.length<16||code.length>16384) throw new ApiError(400,"Google authorization code is invalid");const response=await callGateway("/studio-connected-compute/google/exchange",{method:"POST",body:JSON.stringify({externalUserId:c.user.id,externalWorkspaceId:c.workspaceId,code,label:label||"Google Cloud Shell"})});return json(req,await expectJson(response,"Connected Compute Google exchange"),response.status);}
  if(req.method==="GET"&&path==="/connections"){const response=await callGateway("/studio-connected-compute/connections",{method:"GET",headers:gatewayScope(c)});return json(req,await expectJson(response,"Connected Compute connections"),response.status);}
  const disconnect=path.match(/^\/connections\/([0-9a-f-]{36})$/i);if(req.method==="DELETE"&&disconnect){const response=await callGateway(`/studio-connected-compute/connections/${disconnect[1]}`,{method:"DELETE",headers:gatewayScope(c)});return json(req,await expectJson(response,"Connected Compute connection removal"),response.status);}
  const latest=path.match(/^\/projects\/([0-9a-f-]{36})\/runs\/latest$/i);if(req.method==="GET"&&latest){const p=await project(c,latest[1]);const result=await c.db.from("griot_studio_compute_runs").select("internal_run_id,runtime_id,connection_id,provider,repository_full_name,repository_ref,source_commit_sha,source_tree_sha,status,created_at,updated_at,finished_at").eq("workspace_id",c.workspaceId).eq("project_id",p.id).eq("user_id",c.user.id).order("created_at",{ascending:false}).limit(1).maybeSingle();if(result.error) throw new ApiError(500,"Could not load the latest Connected Compute run");if(!result.data) return json(req,{run:null});return json(req,{run:{id:result.data.internal_run_id,runtimeId:result.data.runtime_id,connectionId:result.data.connection_id,provider:result.data.provider,repository:result.data.repository_full_name,ref:result.data.repository_ref,sourceCommitSha:result.data.source_commit_sha,sourceTreeSha:result.data.source_tree_sha,status:result.data.status,createdAt:result.data.created_at,updatedAt:result.data.updated_at,finishedAt:result.data.finished_at},events:`/functions/v1/griot-studio-compute/runs/${result.data.internal_run_id}/events?projectId=${encodeURIComponent(p.id)}`});}

  const permissions=path.match(/^\/projects\/([0-9a-f-]{36})\/permissions$/i);
  if(req.method==="GET"&&permissions) return json(req,{fullAccess:await agentFullAccess(c,permissions[1]),scope:"connected_project_workspace"});
  if(req.method==="PUT"&&permissions){const input=await body(req);if(typeof input.fullAccess!=="boolean") throw new ApiError(400,"fullAccess must be boolean");await setAgentFullAccess(c,permissions[1],input.fullAccess);return json(req,{fullAccess:input.fullAccess,scope:"connected_project_workspace"});}

  const workspaceFiles=path.match(/^\/projects\/([0-9a-f-]{36})\/workspace\/files$/i);if(req.method==="GET"&&workspaceFiles) return proxyProjectWorkspace(req,c,workspaceFiles[1],"files","GET");
  const workspaceContents=path.match(/^\/projects\/([0-9a-f-]{36})\/workspace\/all-contents$/i);if(req.method==="GET"&&workspaceContents) return proxyProjectWorkspace(req,c,workspaceContents[1],"all-contents","GET");
  const workspaceRead=path.match(/^\/projects\/([0-9a-f-]{36})\/workspace\/file\/read$/i);if(req.method==="POST"&&workspaceRead) return proxyProjectWorkspace(req,c,workspaceRead[1],"file/read","POST");
  const workspaceWrite=path.match(/^\/projects\/([0-9a-f-]{36})\/workspace\/file\/write$/i);if(req.method==="POST"&&workspaceWrite) return proxyProjectWorkspace(req,c,workspaceWrite[1],"file/write","POST");
  const workspaceDelete=path.match(/^\/projects\/([0-9a-f-]{36})\/workspace\/file$/i);if(req.method==="DELETE"&&workspaceDelete) return proxyProjectWorkspace(req,c,workspaceDelete[1],"file","DELETE");
  const workspaceRename=path.match(/^\/projects\/([0-9a-f-]{36})\/workspace\/file\/rename$/i);if(req.method==="POST"&&workspaceRename) return proxyProjectWorkspace(req,c,workspaceRename[1],"file/rename","POST");

  const agentTool=path.match(/^\/projects\/([0-9a-f-]{36})\/agent\/tool$/i);
  if(req.method==="POST"&&agentTool){
    await requireAgentBridge(req);const input=await body(req),tool=String(input.tool||""),projectId=agentTool[1],toolInput=input.input&&typeof input.input==="object"&&!Array.isArray(input.input)?input.input as Row:{};const fullAccess=await agentFullAccess(c,projectId);
    const mutation=tool==="workspace.write"||tool==="workspace.delete"||tool==="workspace.rename"||tool==="archive.extract";
    if(mutation&&!fullAccess) throw new ApiError(409,"GRIOT agent workspace writes require Full Access for this project. Read/verify tools remain available; the user can also apply proposed files manually.");
    const synthetic=new Request(req.url,{method:tool==="workspace.delete"?"DELETE":"POST",headers:req.headers,body:JSON.stringify(toolInput)});
    if(tool==="workspace.read") return proxyProjectWorkspace(synthetic,c,projectId,"file/read","POST","agent");
    if(tool==="workspace.write") return proxyProjectWorkspace(synthetic,c,projectId,"file/write","POST","agent");
    if(tool==="workspace.delete") return proxyProjectWorkspace(synthetic,c,projectId,"file","DELETE","agent");
    if(tool==="workspace.rename") return proxyProjectWorkspace(synthetic,c,projectId,"file/rename","POST","agent");
    if(tool==="archive.extract") return proxyProjectWorkspace(synthetic,c,projectId,"archive/extract","POST","agent");
    if(tool==="workspace.list"){const ready=await latestReadyRun(c,projectId),runId=String(ready.internal_run_id||"");const response=await callGateway(`/studio-connected-compute/runs/${runId}/workspace/files`,{method:"GET",headers:{...gatewayScope(c,projectId),"x-griot-runtime-actor":"agent"}});return json(req,await expectJson(response,"Connected Compute workspace list"),response.status);}
    if(tool==="command.execute"||tool==="test.run"||tool==="build.run") return executeAgentCommand(req,c,projectId,toolInput,fullAccess);
    throw new ApiError(400,"Unknown or unavailable Studio agent tool");
  }

  const start=path.match(/^\/projects\/([0-9a-f-]{36})\/runs$/i);if(req.method==="POST"&&start){const p=await project(c,start[1]);if(p.owner_id!==c.user.id&&!["owner","admin"].includes(c.role)) throw new ApiError(403,"Project execution is not allowed");const input=await body(req),objective=String(input.objective||"").trim();if(!objective||objective.length>20000) throw new ApiError(400,"Execution objective must contain 1-20000 characters");if(input.connectionId&&!uuid(input.connectionId)) throw new ApiError(400,"Connected Compute connection id is invalid");const authority=await callStudioAssertion(req,c,p.id,objective,input.connectionId?String(input.connectionId):undefined),runtimeProvider=String(authority.runtimeProvider||"container"),runPath=runtimeProvider==="container"?"/studio-connected-compute/runs":runtimeProvider==="cloud_run"?"/studio-connected-compute/cloud-run/runs":"/studio-connected-compute/runs";const gateway=await callGateway(runPath,{method:"POST",body:JSON.stringify({assertion:authority.assertion,objective,...(input.connectionId?{connectionId:String(input.connectionId)}:{})}),signal:AbortSignal.timeout(10*60_000)});const started=await expectJson(gateway,"Connected Compute run start"),run=started.run as Row|undefined;if(!run||!uuid(run.id)||!uuid(run.taskId)||!uuid(run.runtimeId)||!uuid(run.connectionId)) throw new ApiError(502,"Execution gateway returned an invalid run identity");const provider=String(run.provider||"").trim();if(!provider) throw new ApiError(502,"Execution gateway returned no runtime provider");const saved=await c.db.from("griot_studio_compute_runs").insert({workspace_id:c.workspaceId,project_id:p.id,user_id:c.user.id,internal_run_id:run.id,internal_task_id:run.taskId,runtime_id:run.runtimeId,connection_id:run.connectionId,provider,repository_full_name:String(run.repository||""),repository_ref:String(run.ref||""),source_commit_sha:String(run.sourceCommitSha||"").toLowerCase(),source_tree_sha:String(run.sourceTreeSha||"").toLowerCase(),status:"ready"}).select("id,internal_run_id,runtime_id,connection_id,status,created_at").single();if(saved.error||!saved.data){console.error("griot-studio-compute-run-map",saved.error?.message||"no mapping row");throw new ApiError(500,"Connected Compute run started but its Studio mapping could not be persisted");}return json(req,{run:{id:run.id,runtimeId:run.runtimeId,connectionId:run.connectionId,state:run.state,provider:run.provider,repository:run.repository,ref:run.ref,sourceCommitSha:run.sourceCommitSha,sourceTreeSha:run.sourceTreeSha,sourceTrust:run.sourceTrust},events:`/functions/v1/griot-studio-compute/runs/${run.id}/events?projectId=${encodeURIComponent(p.id)}`},201);}
  const execute=path.match(/^\/runs\/([0-9a-f-]{36})\/execute$/i);if(req.method==="POST"&&execute){const projectId=new URL(req.url).searchParams.get("projectId")||"";if(!uuid(projectId)) throw new ApiError(400,"projectId is required to execute a Connected Compute command");await runMapping(c,execute[1],projectId);const input=await body(req),response=await callGateway(`/studio-connected-compute/runs/${execute[1]}/execute`,{method:"POST",headers:gatewayScope(c,projectId),body:JSON.stringify(input),signal:AbortSignal.timeout(24*60*60_000)}),payload=await expectJson(response,"Connected Compute execution"),state=String(payload.state||"");if(state==="approval_required") await c.db.from("griot_studio_compute_runs").update({status:"approval_required",updated_at:new Date().toISOString()}).eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("internal_run_id",execute[1]).eq("user_id",c.user.id);else if(state==="completed") await c.db.from("griot_studio_compute_runs").update({status:"ready",updated_at:new Date().toISOString()}).eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("internal_run_id",execute[1]).eq("user_id",c.user.id);return json(req,payload,response.status);}
  const approval=path.match(/^\/runs\/([0-9a-f-]{36})\/approvals\/([0-9a-f-]{36})$/i);if(req.method==="POST"&&approval){const projectId=new URL(req.url).searchParams.get("projectId")||"";if(!uuid(projectId)) throw new ApiError(400,"projectId is required for a Connected Compute approval");await runMapping(c,approval[1],projectId);const input=await body(req),response=await callGateway(`/studio-connected-compute/runs/${approval[1]}/approvals/${approval[2]}`,{method:"POST",headers:gatewayScope(c,projectId),body:JSON.stringify(input)}),payload=await expectJson(response,"Connected Compute approval"),decision=String(input.decision||"");await c.db.from("griot_studio_compute_runs").update({status:decision==="approved"?"ready":"blocked",updated_at:new Date().toISOString()}).eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("internal_run_id",approval[1]).eq("user_id",c.user.id);return json(req,payload,response.status);}
  const previewStart=path.match(/^\/runs\/([0-9a-f-]{36})\/preview\/start$/i);if(req.method==="POST"&&previewStart){const projectId=new URL(req.url).searchParams.get("projectId")||"";if(!uuid(projectId)) throw new ApiError(400,"projectId is required to start preview");await runMapping(c,previewStart[1],projectId);const response=await callGateway(`/studio-connected-compute/runs/${previewStart[1]}/preview/start`,{method:"POST",headers:gatewayScope(c,projectId),signal:AbortSignal.timeout(120000)});return json(req,await expectJson(response,"Connected Compute preview start"),response.status);}
  const previewStop=path.match(/^\/runs\/([0-9a-f-]{36})\/preview\/stop$/i);if(req.method==="POST"&&previewStop){const projectId=new URL(req.url).searchParams.get("projectId")||"";if(!uuid(projectId)) throw new ApiError(400,"projectId is required to stop preview");await runMapping(c,previewStop[1],projectId);const response=await callGateway(`/studio-connected-compute/runs/${previewStop[1]}/preview/stop`,{method:"POST",headers:gatewayScope(c,projectId)});return json(req,await expectJson(response,"Connected Compute preview stop"),response.status);}
  const preview=path.match(/^\/runs\/([0-9a-f-]{36})\/preview$/i);if(req.method==="GET"&&preview){const projectId=new URL(req.url).searchParams.get("projectId")||"";if(!uuid(projectId)) throw new ApiError(400,"projectId is required to load preview");await runMapping(c,preview[1],projectId);const response=await callGateway(`/studio-connected-compute/runs/${preview[1]}/preview`,{method:"GET",headers:gatewayScope(c,projectId)});return json(req,await expectJson(response,"Connected Compute preview"),response.status);}
  const stop=path.match(/^\/runs\/([0-9a-f-]{36})\/stop$/i);if(req.method==="POST"&&stop){const projectId=new URL(req.url).searchParams.get("projectId")||"";if(!uuid(projectId)) throw new ApiError(400,"projectId is required to stop a Connected Compute run");await runMapping(c,stop[1],projectId);const response=await callGateway(`/studio-connected-compute/runs/${stop[1]}/stop`,{method:"POST",headers:gatewayScope(c,projectId)}),payload=await expectJson(response,"Connected Compute stop");if(response.ok) await c.db.from("griot_studio_compute_runs").update({status:"cancelled",updated_at:new Date().toISOString(),finished_at:new Date().toISOString()}).eq("workspace_id",c.workspaceId).eq("project_id",projectId).eq("internal_run_id",stop[1]).eq("user_id",c.user.id);return json(req,payload,response.status);}
  const events=path.match(/^\/runs\/([0-9a-f-]{36})\/events$/i);if(req.method==="GET"&&events){const runId=events[1],projectId=new URL(req.url).searchParams.get("projectId")||"";if(!uuid(projectId)) throw new ApiError(400,"projectId is required for the Live Work stream");await runMapping(c,runId,projectId);const after=new URL(req.url).searchParams.get("after")||req.headers.get("last-event-id")||"0";if(!/^\d{1,20}$/.test(after)) throw new ApiError(400,"Event cursor is invalid");const upstream=await callGateway(`/studio-connected-compute/runs/${runId}/events?after=${encodeURIComponent(after)}`,{method:"GET",headers:gatewayScope(c,projectId),signal:AbortSignal.timeout(12*60*60_000)});if(!upstream.ok||!upstream.body){const failure=await expectJson(upstream,"Connected Compute Live Work stream");return json(req,failure,upstream.status);}const headers=cors(req);headers.set("content-type","text/event-stream; charset=utf-8");headers.set("cache-control","no-cache, no-store, must-revalidate");headers.set("x-accel-buffering","no");return new Response(upstream.body,{status:200,headers});}
  throw new ApiError(404,"Studio Connected Compute route not found");
}
function uuid(value:unknown):value is string{return typeof value==="string"&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);}
Deno.serve(async(req)=>{try{return await dispatch(req);}catch(error){if(error instanceof ApiError)return json(req,{error:error.message},error.status);console.error("griot-studio-compute",error);return json(req,{error:"Internal server error"},500);}});