import type { SupabaseClient } from "npm:@supabase/supabase-js@^2";
import { compileMissionIntent } from "./compiler.ts";
import { executeWorkUnitChip } from "./chips.ts";
import { PostgresBlackboard } from "./blackboard.ts";
import { evaluateMissionConvergence } from "./convergence.ts";
import { BlackboardEvent, CompositionCertificate, MissionIntent, WorkUnitV1 } from "./types.ts";
export interface MissionRunProgressCallback { (event: BlackboardEvent): void; }
export interface MissionRunResult { missionId:string; status:"converged"|"disputed"|"failed"; summary:string; canonicalSolution:string; certificate:CompositionCertificate; totalTokens:number; costGcu:number; durationMs:number; }
export async function runModelGpuMission(missionId:string,intent:MissionIntent,supabase:SupabaseClient,apiKeys:{gemini?:string;openai?:string;anthropic?:string;groq?:string},onProgress?:MissionRunProgressCallback):Promise<MissionRunResult>{
 const missionStartTime=performance.now(); const blackboard=new PostgresBlackboard(missionId,supabase); await blackboard.init();
 const emit=async(eventType:BlackboardEvent["eventType"],wave:number,payload:Record<string,unknown>):Promise<BlackboardEvent>=>{const event=await blackboard.emitEvent(eventType,wave,payload);try{onProgress?.(event);}catch(err){console.error("[Engine] onProgress handler error:",err);}return event;};
 const dag=compileMissionIntent(missionId,intent); await emit("mission_started",0,{objective:intent.objective,strategy:intent.strategy,totalUnits:dag.totalUnits});
 await supabase.from("griot_gpu_missions").update({status:"wave_1",current_wave:1,updated_at:new Date().toISOString()}).eq("id",missionId); await emit("wave_started",1,{units:dag.waves.wave1.map(u=>u.id)});
 const executeUnit=async(unit:WorkUnitV1):Promise<WorkUnitV1>=>{unit.status="running";await emit("work_unit_dispatched",unit.wave,{unitId:unit.id,role:unit.role,model:unit.modelId});try{const res=await executeWorkUnitChip(unit,apiKeys);unit.status="succeeded";unit.output=res.output;unit.rawText=res.rawText;unit.usage=res.usage;unit.durationMs=res.durationMs;await emit("work_unit_completed",unit.wave,{unitId:unit.id,role:unit.role,durationMs:res.durationMs,usage:res.usage,summary:res.output.summary});}catch(err:any){unit.status="failed";unit.error=err.message||String(err);console.error(`[Engine] Work unit ${unit.id} failed:`,err);await emit("work_unit_completed",unit.wave,{unitId:unit.id,role:unit.role,status:"failed",error:unit.error});}return unit;};
 const wave1Results=await Promise.all(dag.waves.wave1.map(executeUnit)); await emit("wave_completed",1,{completedUnits:wave1Results.map(u=>({id:u.id,status:u.status}))});
 const successfulWave1=wave1Results.filter(u=>u.status==="succeeded"); if(successfulWave1.length===0){const errorMsg="All Wave 1 exploration trajectories failed";await emit("mission_failed",1,{error:errorMsg});await supabase.from("griot_gpu_missions").update({status:"failed",error_message:errorMsg,updated_at:new Date().toISOString()}).eq("id",missionId);throw new Error(errorMsg);}
 await supabase.from("griot_gpu_missions").update({status:"wave_2",current_wave:2,updated_at:new Date().toISOString()}).eq("id",missionId); await emit("wave_started",2,{units:["unit_w2_synthesis"]});
 const unit2=dag.waves.wave2[0]; const alphaOutput=wave1Results.find(u=>u.id==="unit_w1_alpha")?.output; const betaOutput=wave1Results.find(u=>u.id==="unit_w1_beta")?.output;
 unit2.prompt=`MISSION OBJECTIVE:\n${intent.objective}\n\nTRAJECTORY ALPHA PROPOSAL:\nSummary: ${alphaOutput?.summary||"N/A"}\nSolution:\n${alphaOutput?.solution||"N/A"}\nProposed Actions: ${JSON.stringify(alphaOutput?.proposedActions||[])}\nRisks Identified: ${JSON.stringify(alphaOutput?.risks||[])}\n\nTRAJECTORY BETA PROPOSAL:\nSummary: ${betaOutput?.summary||"N/A"}\nSolution:\n${betaOutput?.solution||"N/A"}\nProposed Actions: ${JSON.stringify(betaOutput?.proposedActions||[])}\nRisks Identified: ${JSON.stringify(betaOutput?.risks||[])}\n\nSynthesize these independent viewpoints into the definitive, robust Canonical Solution.`;
 const wave2Result=await executeUnit(unit2);await emit("wave_completed",2,{status:wave2Result.status}); if(wave2Result.status!=="succeeded"){const errorMsg="Wave 2 Canonical Synthesis failed";await emit("mission_failed",2,{error:errorMsg});await supabase.from("griot_gpu_missions").update({status:"failed",error_message:errorMsg,updated_at:new Date().toISOString()}).eq("id",missionId);throw new Error(errorMsg);}
 await supabase.from("griot_gpu_missions").update({status:"wave_3",current_wave:3,updated_at:new Date().toISOString()}).eq("id",missionId);await emit("wave_started",3,{units:["unit_w3_auditor"]});
 const unit3=dag.waves.wave3[0];const synthOutput=wave2Result.output;unit3.prompt=`MISSION OBJECTIVE:\n${intent.objective}\n\nACCEPTANCE CRITERIA:\n${intent.acceptanceCriteria.map((c,i)=>`[Criterion ${c.id||i+1} (${c.verificationClass})]: ${c.description}`).join("\n")}\n\nCANONICAL SOLUTION UNDER REVIEW:\nSummary: ${synthOutput?.summary}\nSolution:\n${synthOutput?.solution}\nActions: ${JSON.stringify(synthOutput?.proposedActions)}\nMitigated Risks: ${JSON.stringify(synthOutput?.risks)}\n\nPerform a strict independent audit of this Canonical Solution against the criteria. Highlight edge cases, contradictions, or unaddressed risks.`;
 const wave3Result=await executeUnit(unit3);await emit("wave_completed",3,{status:wave3Result.status});const certificate=await evaluateMissionConvergence({missionId,wave1Units:wave1Results,wave2Unit:wave2Result,wave3Auditor:wave3Result,blackboardTerminalHash:blackboard.getLastHash()});await emit("convergence_evaluated",3,{certificateId:certificate.certificateId,rootSha256:certificate.rootSha256,deterministicScore:certificate.deterministicScore,status:certificate.status});
 const allUnits=[...wave1Results,wave2Result,wave3Result];let totalTokens=0;for(const u of allUnits)totalTokens+=u.usage?.totalTokens||0;const costGcu=Math.max(.1,Math.round((totalTokens/2000)*100)/100);const durationMs=Math.round(performance.now()-missionStartTime);const finalSummary=wave2Result.output?.summary||"Mission completed";const finalSolution=wave2Result.output?.solution||wave2Result.rawText||"";
 await supabase.from("griot_gpu_missions").update({status:"converged",certificate:certificate as any,summary:finalSummary,cost_gcu:costGcu,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("id",missionId);await emit("mission_succeeded",3,{certificateId:certificate.certificateId,durationMs,totalTokens,costGcu});return{missionId,status:certificate.status==="disputed"?"disputed":"converged",summary:finalSummary,canonicalSolution:finalSolution,certificate,totalTokens,costGcu,durationMs}; }

