import { z } from "npm:zod@^3.23.8";

export const SafeIdSchema = z.string().min(1).max(128).regex(/^[a-zA-Z0-9][a-zA-Z0-9._:-]*$/);
export const ChipClaimSchema = z.object({ criterionId: z.string().min(1).max(128), verdict: z.enum(["supports", "contradicts", "uncertain"]), confidence: z.number().min(0).max(1), rationale: z.string().min(1).max(20000), evidence: z.array(z.string().min(1).max(4000)).default([]) });
export const ChipContributionSchema = z.object({ summary: z.string().min(1).max(50000), solution: z.string().default(""), claims: z.array(ChipClaimSchema).default([]), proposedActions: z.array(z.string().min(1).max(10000)).default([]), risks: z.array(z.string().min(1).max(10000)).default([]), verificationSteps: z.array(z.string().min(1).max(10000)).default([]) });
export type ChipContribution = z.infer<typeof ChipContributionSchema>;
export const MissionIntentSchema = z.object({ objective: z.string().trim().min(3).max(20000), workspaceId: z.string().uuid().optional(), projectId: z.string().uuid().optional(), effort: z.enum(["low","medium","high"]).default("medium"), strategy: z.enum(["maximum_quality","balanced","maximum_speed"]).default("maximum_quality"), constraints: z.array(z.string().trim().max(1000)).default([]), acceptanceCriteria: z.array(z.object({ id:z.string().min(1).max(128), description:z.string().min(1).max(2000), verificationClass:z.enum(["deterministic","human","hybrid"]).default("hybrid") })).default([]), preferredModels:z.object({wave1Alpha:z.string().optional(),wave1Beta:z.string().optional(),wave2Synthesis:z.string().optional(),wave3Auditor:z.string().optional()}).default({}) });
export type MissionIntent = z.infer<typeof MissionIntentSchema>;
export interface WorkUnitV1 { id:string; wave:1|2|3; role:"independent_trajectory"|"canonical_synthesis"|"independent_auditor"; providerId:string; modelId:string; objective:string; prompt:string; systemPrompt:string; dependsOn:string[]; status:"pending"|"running"|"succeeded"|"failed"; output?:ChipContribution; rawText?:string; error?:string; usage?:{inputTokens:number|null;outputTokens:number|null;reasoningTokens:number|null;totalTokens:number|null};durationMs?:number; }
export interface CompositionCertificate { certificateId:string; missionId:string; rootSha256:string; deterministicScore:number; confidenceScore:number; status:"converged"|"disputed"|"conditional"; waveReceipts:Array<{wave:number;unitId:string;model:string;outputHash:string;status:string}>; auditedCriteria:Array<{id:string;verdict:"passed"|"failed"|"unverified";rationale:string}>; issuedAt:string; }
export interface BlackboardEvent { sequence:number; eventType:"mission_started"|"wave_started"|"work_unit_dispatched"|"work_unit_completed"|"wave_completed"|"convergence_evaluated"|"mission_succeeded"|"mission_failed"; wave:number; previousHash:string; eventHash:string; payload:Record<string,unknown>; createdAt:string; }

